import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "@/utils/trpc";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Pokevolve</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col justify-between relative items-center text-xl text-center pb-2">
        <span>Hello World!</span>
        <div className="w-full text-xl text-center pb-2">
          <a href="https://twitter.com/ImKurtwood">Twitter</a>
          <span className="mx-2">-</span>
          <a href="https://github.com/Mattszczp/pokevolve">Github</a>
        </div>
      </div>
    </>
  );
};

export default Home;
